name: Pull request deploy
on:
  pull_request:
    types: [opened, reopened, closed, synchronize]

jobs:
  pr_deploy:
    runs-on: ubuntu-latest
    name: Deploying PR
    steps:
      - uses: actions/checkout@v4
      - id: workflow
        uses: ./
        with:
          server_host: ${{ secrets.HOST }}
          server_username: ${{ secrets.USERNAME  }}
          server_password: ${{ secrets.PASSWORD  }}
          server_port: ${{ secrets.PORT  }}
          dir: "."
          dockerfile: "Dockerfile"
          # compose_file: ${{ variables.docker_compose }}
          exposed_port: "3000"
          branch_name: ${{ github.pull_request.head.ref }}
          repo_url: ${{ github.pull_request.head.repo.clone_url }}
          pr_number: ${{ github.event.pull_request.number }}
          # env: ${{ env }}
